# 列表/字典/集合操作

#  1、筛选数据

In [13]:
from random import randint
data = [randint(-5,20) for _ in range(10)]   #列表筛选

#剔除负数
%timeit [x for x in data if x>=0]     
%timeit  filter(lambda x: x>=0 ,data)
# print(d)
# list(d1)

1.23 µs ± 6.74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
437 ns ± 7.71 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
from random import randint
data = {x:randint(60,100) for x in range(1,21)}   #生成字典
d={k:v for k,v in data.items() if v>90}        #筛选大于90的数

In [19]:
d

{3: 95, 4: 96, 5: 100, 6: 91, 7: 95, 9: 92, 12: 97, 20: 100}

# 2、数据统计

In [23]:
from collections import namedtuple                #元组----内置元组
Student = namedtuple('Student',['name','sex','age','email'])
s=Student('jack','male',16,'2344@qq.com')
s.age

16

In [17]:
from random import randint
data = [randint(2,10) for _ in range(30)]

In [34]:
c=dict.fromkeys(data,0)        #&&&&&&&&& 重点 &&&&&&&&  获取字典的项，并赋予每个项初值。
for i in data:     #统计每个项出现的次数
    c[i]+=1
print(c)

{9: 3, 4: 4, 8: 4, 10: 3, 5: 2, 7: 4, 2: 3, 3: 3, 6: 4}


In [55]:
from collections import Counter
c2=Counter(data)   #直接对data进行次数统计
c2.most_common(3)   #出现次数最多的3（n）个

[(4, 4), (8, 4), (7, 4)]

In [51]:
import re               #文件词频统计   ********
txt=open('./readme.txt','r',encoding='utf-8').read()
c3=Counter(re.split('\W+',txt))   #正则表达式分割非字母文字

In [52]:
c3.most_common(2)

[('', 2), ('example_learn1', 1)]

In [53]:
re.split('\W+',txt)

['', 'example_learn1', '鼠标操作', '文件夹的压缩', '解压', '重命名', '删除', '复制', '']

# 3、 根据字典值的大小对字典排序

#使用zip将字典转化为元组
#使用sorted函数的key参数

In [62]:
from random import randint
data = {x:randint(60,100) for x in 'xyzabc'}
# data.keys()   #字典的键
# data.values() #字典的值

In [74]:
d = list(zip(data.values(),data.keys()))   #使用zip将字典的值和键互换
sorted(zip(data.values(),data.keys()))     #排序

[(64, 'y'), (74, 'b'), (81, 'z'), (92, 'x'), (96, 'a'), (97, 'c')]

In [76]:
data.items()

dict_items([('x', 92), ('y', 64), ('z', 81), ('a', 96), ('b', 74), ('c', 97)])

In [75]:
sorted(data.items(),key = lambda x:x[1])

[('y', 64), ('b', 74), ('z', 81), ('x', 92), ('a', 96), ('c', 97)]

#  4、多个字典公共键（key）

In [77]:
from random import randint , sample
sample('asdfrgtkl',randint(3,6))  #从'asdfrgtkl' 随机 获取3-6个值

['d', 's', 'f']

In [79]:
s1 = {x:randint(1,4) for x in sample('asdfrgtkl',randint(3,6)) }
s2 = {x:randint(1,4) for x in sample('asdfrgtkl',randint(3,6)) }
s3 = {x:randint(1,4) for x in sample('asdfrgtkl',randint(3,6)) }
print(s1,s2,s3)

{'r': 2, 'g': 4, 'l': 1} {'a': 2, 'f': 2, 'r': 4, 'd': 1} {'g': 1, 'f': 3, 'd': 3, 'l': 3, 'r': 3}


In [84]:
s1.keys()&s2.keys()&s3.keys()     #集合'并'运算 ，适合字典数目较少

{'r'}

In [86]:
list(map(dict.keys,[s1,s2,s3]))

[dict_keys(['r', 'g', 'l']),
 dict_keys(['a', 'f', 'r', 'd']),
 dict_keys(['g', 'f', 'd', 'l', 'r'])]

In [88]:
from functools import reduce
reduce(lambda a,b: a & b, map(dict.keys,[s1,s2,s3]))

{'r'}

In [2]:
from collections import Counter
nums = [1,1,1,3,4,6,7,7,2,4]
# c = Counter(nums)
c1 = sorted(Counter(nums).items() , key = lambda x : (x[1],-x[0]))     ##对数据c[1]升序排列，对c[0]降序排列  
c2 = [i for i,k in c1]
c3 = [i  for j in c2 for i in nums if j==i]
c3

[6, 3, 2, 7, 7, 4, 4, 1, 1, 1]

In [20]:
s = "a"

t = "a"
s1 = dict.fromkeys(s,0)
t1 = dict.fromkeys(t,0)
for i in s:
    s1[i]+=1
for i in t:
    t1[i]+=1
r = s1==t1 and 1 or 2
r

1

In [8]:
points = [[10,16],[2,8],[1,6],[7,12]]
c = []
s = []
for i in points:
    c.append([j for j in range(i[0],i[1]+1)])

for i in range(1,len(c)+1):
    for j in range(i,len(c)):
        same = []
        same = [k for k in c[i-1] if k in c[j]]
        if len(same) > 0: 
            s.append(same)
s


IndexError: list index out of range

In [5]:
points = [[5,16],[2,8],[3,6],[6,12]]
def findMinArrowShots(points) :
    if points == []:
        return 0
    points.sort()
    start , end = points[0][0] , points[0][1]
    arrow = 1
    for i in points[1:]:
        if i[0] > end:
            arrow += 1
            end = i[1]
        else:
            if i[1]  < end :
                end = i[1]
    return arrow
findMinArrowShots(points)

1

In [33]:
S = 'aasda'
c=Counter(S)
res = ""
j = 0
if 2*list(c.values())[0] -len(S) > 1:
    print(0)
else :
    while(j<len(S)):
        for i,k in c.items():
            if j/len(c) < k:
                res += i
                j += 1
res

'asdaa'

In [15]:
from collections import Counter
S = 'aasd'
c=Counter(S)
c

Counter({'a': 2, 's': 1, 'd': 1})

In [27]:
list(c.values())[0]


1

In [47]:
import numpy
nums = [128,128,128,128]
target = 256
s = []
# nums.sort()
n = numpy.array(nums)
if len(nums)==1:
    print(0)
for i in range(len(nums)):
    t = nums[i]
    j = target - t
    n[i] = - 10**5
    print(n)
    if j in n :
        p = numpy.where(n[:] == j)
        x = p[0][-1]
        s.append([t,j])
        n[x] = - 10**5
        print(x,n)
s

[-100000     128     128     128]
3 [-100000     128     128 -100000]
[-100000 -100000     128 -100000]
2 [-100000 -100000 -100000 -100000]
[-100000 -100000 -100000 -100000]
[-100000 -100000 -100000 -100000]


[[128, 128], [128, 128]]

In [51]:
import numpy
nums = [128,128,128,128]
target = 256
s = []
nums.sort()
n = numpy.array(nums)
i = 0
j = len(nums)
while i < j:
    t = nums[i]
    r = target - t
    if r in n:
        p = numpy.where(n[:] == r)
        x = p[0][-1]
        j = x
        i = i + 1
        s.append([t,r])
        n[x] = - 10**5
        print(x,n)
        
s       
    

3 [    128     128     128 -100000]
2 [    128     128 -100000 -100000]


[[128, 128], [128, 128]]

In [36]:
n

array([-100000, -100000, -100000, -100000])